var path = require('path')

module.exports = function (service, context, data) {
  var serviceStartPath = data.services[service]
    , envVars = []
    , header =
        [ '# THIS FILE IS AUTOMATICALLY GENERATED BY NAVY - DO NOT MANUALLY EDIT'
        , 'description "' + service + ' ' + context.appId + ' ' + data.environment + '"'
        , ''
        , 'env NODE_ENV=' + data.environment
        , 'env NODE_START=' + path.join(data.finalDir, serviceStartPath)
        , 'env NODE_VERSION=v' + data.nodeVersion
        , ''
        ].join('\n')

  if (data.customEnvVars) {
    envVars.push('')
    Object.keys(data.customEnvVars).forEach(function (key) {
      var envLine = 'env '
      envLine += key + '='
      envLine += data.customEnvVars[key]
      envVars.push(envLine)
    })
    envVars.push('')
  }

  var footer =
    [ ''
    , 'setuid node'
    , 'env HOME=/home/node'
    , ''
    , 'start on (local-filesystems and net-device-up IFACE=eth0)'
    , 'stop  on shutdown'
    , ''
    , 'respawn                # restart when job dies'
    , 'respawn limit 5 60     # give up restart after 5 respawns in 60 seconds'
    , ''
    , 'exec /usr/local/bin/nave use $NODE_VERSION node $NODE_START'
    ].join('\n')

  return header + envVars.join('\n') + footer
}
